# Generated by Django 4.2.6 on 2023-11-02 18:45

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reward_task_delete_rewards'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attending',
            field=models.ManyToManyField(related_name='event_attending', to='main.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation',
            field=models.FileField(blank=True, null=True, upload_to='events/invitations/'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(related_name='event_invited', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('open', 'open'), ('invitation', 'invitation')], max_length=50),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attended_by', models.ManyToManyField(related_name='meetings_attended', to='main.position')),
                ('departments', models.ManyToManyField(related_name='meetings', to='main.department')),
                ('members', models.ManyToManyField(related_name='meetings_invited', to='main.position')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
