# Generated by Django 4.1.4 on 2023-12-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='company_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='site',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='site',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tagline',
        ),
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='site',
            name='no_of_employees',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of Employees'),
        ),
        migrations.AddField(
            model_name='site',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Phone Number'),
        ),
        migrations.AddField(
            model_name='site',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Type'),
        ),
    ]
