# Generated by Django 4.2.6 on 2023-10-21 22:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_admin_alter_event_date_alter_news_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Title')),
                ('tagline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('about', tinymce.models.HTMLField(blank=True, null=True, verbose_name='About Organization')),
                ('objectives', tinymce.models.HTMLField(blank=True, null=True)),
                ('mission', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='featured',
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='directions',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
