# Generated by Django 4.1.4 on 2023-11-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_event_attending_event_invitation_event_invitees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
