# Generated by Django 4.2.6 on 2023-10-21 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_site_remove_news_featured_event_link_news_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='site',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='site',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
