# Generated by Django 4.1.4 on 2023-11-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_assigned_to_alter_task_completed_by'),
        ('admins', '0003_site_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='attended_by',
            field=models.ManyToManyField(blank=True, related_name='meetings_attended', to='main.position'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='main.department'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='meetings_invited', to='main.position'),
        ),
    ]
