# Generated by Django 4.2.6 on 2023-10-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_event_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
