# Generated by Django 4.1.4 on 2023-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
