# Generated by Django 4.1.4 on 2023-12-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_forgottenpassword'),
        ('admins', '0007_remove_event_attending_remove_event_invitees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.BigIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['level', 'id'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='main.profile'),
        ),
        migrations.AddField(
            model_name='site',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_sites', to='admins.plan'),
        ),
    ]
