# Generated by Django 4.2.6 on 2023-10-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_position_remove_profile_job_role_rewards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Engr', 'Engr'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Prof', 'Prof')], max_length=100, null=True),
        ),
    ]
