# Generated by Django 4.1.4 on 2023-11-04 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reward_task_delete_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('proposed_solution', models.TextField(blank=True, null=True)),
                ('addressed', models.BooleanField(default=False)),
                ('solution', tinymce.models.HTMLField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='main.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
