# Generated by Django 4.2.6 on 2023-10-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('main', '0005_alter_profile_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authtoken.token'),
        ),
    ]
