# Generated by Django 4.1.4 on 2023-11-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_description_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks_assigned', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks_completed', to='main.profile'),
        ),
    ]
