# Generated by Django 4.1.4 on 2023-11-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_task_assigned_to_alter_task_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='tasks_completed', to='main.profile'),
        ),
    ]
