# Generated by Django 4.1.4 on 2023-11-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_log_options_remove_reward_owner_reward_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgottenPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgotten_password', to='main.profile')),
            ],
        ),
    ]
